# Cloudflare Worker 配置
name = "dental-pay"
main = "worker.js"
compatibility_date = "2025-01-01"
account_id = "e0f248f67c8de99c72b52ca5c9213418"

[[kv_namespaces]]
binding = "PAY_KV"
id = "c98c6ebc8d2b41278b346a98d173acb5"
