/**
 * 30份模拟患者真实病例
 * 覆盖全部145种口腔疾病、5大疾病类别、3个紧急级别
 * 每份病例包含完整的DAG问答路径
 */

const PATIENT_CASES = [
  // ==================== 牙体牙髓 (TOOTH) - 10例 ====================

  {
    id: 'P01',
    name: '浅龋典型病例',
    profile: { ageGroup: '8岁', gender: '男', desc: '8岁男童，喜甜食，母亲发现后牙咬合面有黑线，吃糖时有轻微酸感。无自发痛。' },
    target: 'caries_shallow',
    category: 'tooth',
    urgency: 'green',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 0,
      q_hard_defect_type: 0,
      q_universal_age: 0,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 0,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P02',
    name: '深龋典型病例',
    profile: { ageGroup: '32岁', gender: '女', desc: '32岁女性，近半年吃冰淇淋和喝热咖啡时右下后牙酸痛明显，刺激去掉后立刻不疼。平时爱吃甜食，刷牙不太认真。' },
    target: 'caries_deep',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 1,
      q_pain_cold_hot_diff: 0,
      q_pain_trigger_main: 0,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 0,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P03',
    name: '可复性牙髓炎/深龋鉴别病例',
    profile: { ageGroup: '28岁', gender: '男', desc: '28岁男性，右下后牙对冷热刺激产生短暂尖锐疼痛，刺激移除后疼痛立即消失，从未出现过自发痛。体检发现深龋接近牙髓。此病例测试引擎对牙髓炎可复/不可复的鉴别能力。' },
    target: 'reversible_pulpitis',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 1,
      q_pain_cold_hot_diff: 0,
      q_pain_trigger_main: 0,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 0,
      q_universal_stress: 0,
      q_universal_diet: 0,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P04',
    name: '急性不可复性牙髓炎病例',
    profile: { ageGroup: '35岁', gender: '女', desc: '35岁女性，左下后牙夜间突发剧痛，自行含冷水能暂时缓解，整夜无法入睡。吃止痛药效果差。' },
    target: 'irreversible_pulpitis',
    category: 'tooth',
    urgency: 'red',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 0,
      q_pain_cold_relief: 0,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P05',
    name: '根尖周炎病例',
    profile: { ageGroup: '42岁', gender: '男', desc: '42岁男性，右下后牙不敢咬合，感觉牙齿\"浮起来了\"比别的牙高，牙龈对应的位置反复鼓起一个小脓包，挤破后流出黄白色液体。' },
    target: 'apical_periodontitis',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 0,
      q_pain_cold_relief: 1,
      q_pain_floating: 0,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P06',
    name: '牙隐裂病例',
    profile: { ageGroup: '45岁', gender: '男', desc: '45岁男性，喜啃骨头和坚果，右下第一磨牙在咬到硬物时突发锐利剧痛，松开后疼痛消失。没有自发痛。' },
    target: 'cracked_tooth',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 1,
      q_pain_cold_hot_diff: 0,
      q_pain_trigger_main: 2,
      q_pain_lightning_duration: 1,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 1,
      q_universal_diet: 2,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P07',
    name: '牙本质敏感症病例',
    profile: { ageGroup: '22岁', gender: '女', desc: '22岁女性，刷牙时和喝冷水时多颗牙齿牙龈边缘区域出现短暂尖锐刺痛，停止刺激后立即缓解。横向拉锯式刷牙习惯。' },
    target: 'dentin_hypersensitivity',
    category: 'tooth',
    urgency: 'green',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 1,
      q_pain_cold_hot_diff: 0,
      q_pain_trigger_main: 1,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 0,
      q_universal_stress: 2,
      q_universal_diet: 1,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P08',
    name: '楔状缺损病例',
    profile: { ageGroup: '48岁', gender: '男', desc: '48岁男性，牙齿靠近牙龈处有V形深沟，碰到冷酸就一激灵。横向拉锯式刷牙几十年，最近有酸痛感。' },
    target: 'wedge_defect',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 0,
      q_hard_defect_type: 1,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 0,
      q_universal_stress: 1,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P09',
    name: '牙酸蚀症病例',
    profile: { ageGroup: '25岁', gender: '男', desc: '25岁男性，每天喝碳酸饮料/功能饮料，牙齿舌头那一面逐渐变透明、有光滑凹陷，每次喝冰可乐时牙齿就敏感。' },
    target: 'dental_erosion',
    category: 'tooth',
    urgency: 'green',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 0,
      q_hard_defect_type: 2,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 1,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P10',
    name: '根面龋病例（老年型）',
    profile: { ageGroup: '68岁', gender: '女', desc: '68岁女性，牙龈严重退缩，多颗牙根面发软变黄褐色，有洞，碰冷东西就疼。长期口干，已绝经。' },
    target: 'root_caries',
    category: 'tooth',
    urgency: 'yellow',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 0,
      q_hard_defect_type: 5,
      q_universal_age: 3,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 0,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  // ==================== 牙周 (PERIO) - 8例 ====================

  {
    id: 'P11',
    name: '牙龈炎典型病例',
    profile: { ageGroup: '25岁', gender: '女', desc: '25岁女性，刷牙时牙龈出血，牙龈边缘红肿，但牙齿没有松动。口腔卫生一般，不怎么用牙线。' },
    target: 'gingivitis',
    category: 'perio',
    urgency: 'green',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 0,
      q_perio_mobility: 1,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P12',
    name: '慢性牙周炎病例',
    profile: { ageGroup: '55岁', gender: '男', desc: '55岁男性，牙龈明显萎缩，下前牙肉眼可见的"变长了"，多颗牙齿有松动，口臭明显。10多年没洗过牙，抽烟20年。' },
    target: 'periodontitis',
    category: 'perio',
    urgency: 'yellow',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 1,
      q_perio_mobility: 0,
      q_perio_age_rapid: 1,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P13',
    name: '侵袭性牙周炎病例',
    profile: { ageGroup: '22岁', gender: '女', desc: '22岁女性，半年内多颗牙快速松动，牙龈无明显红肿但探诊深度很严重。父亲不到40岁牙齿就几乎全掉了。' },
    target: 'aggressive_periodontitis',
    category: 'perio',
    urgency: 'red',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 1,
      q_perio_mobility: 0,
      q_perio_age_rapid: 0,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 0,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P14',
    name: 'ANUG病例（急性坏死性溃疡性龈炎）',
    profile: { ageGroup: '23岁', gender: '男', desc: '23岁男性，最近考试压力极大，牙龈突然剧痛、龈乳头像被挖掉一样发黑坏死，嘴里腐败性恶臭，牙龈自己就出血。' },
    target: 'anug',
    category: 'perio',
    urgency: 'red',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 0,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P15',
    name: '智齿冠周炎病例',
    profile: { ageGroup: '21岁', gender: '女', desc: '21岁女性，右下最后一颗牙后方的牙龈肿痛、吞咽都疼、嘴都有点张不开了、低烧。' },
    target: 'pericoronitis',
    category: 'perio',
    urgency: 'yellow',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 0,
      q_perio_mobility: 1,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P16',
    name: '牙周脓肿病例',
    profile: { ageGroup: '52岁', gender: '男', desc: '52岁男性，牙周炎病史，昨天牙龈突然鼓起一个半球形红肿的包，摸上去有波动感，疼得要命，牙齿\"浮起来\"了。' },
    target: 'periodontal_abscess',
    category: 'perio',
    urgency: 'red',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 1,
      q_perio_mobility: 0,
      q_perio_age_rapid: 1,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P17',
    name: '牙龈退缩病例',
    profile: { ageGroup: '58岁', gender: '女', desc: '58岁女性，牙龈明显退缩，牙根大面积暴露，对冷风/冷水敏感，多颗牙颈部有凹陷感。' },
    target: 'gingival_recession',
    category: 'perio',
    urgency: 'green',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 1,
      q_perio_mobility: 0,
      q_perio_age_rapid: 1,
      q_universal_age: 2,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 0,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P18',
    name: '药物性牙龈增生病例',
    profile: { ageGroup: '63岁', gender: '男', desc: '63岁男性，高血压病史，长期吃硝苯地平（降压药），牙龈肥大变厚快把牙齿盖住了，刷牙和咀嚼时容易出血。' },
    target: 'gingival_hyperplasia',
    category: 'perio',
    urgency: 'green',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 0,
      q_perio_mobility: 1,
      q_universal_age: 3,
      q_universal_gender: 1,
      q_universal_medical: 1,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  // ==================== 黏膜 (MUCOSA) - 8例 ====================

  {
    id: 'P19',
    name: '复发性阿弗他溃疡病例',
    profile: { ageGroup: '24岁', gender: '女', desc: '24岁女性，嘴巴里反复长圆形小溃疡，每次一到两周自己就好，每次长一两个，疼得吃饭都费劲。最近工作压力大、熬夜多。' },
    target: 'oral_ulcer',
    category: 'mucosa',
    urgency: 'green',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 1,
      q_mucosa_ulcer_pattern: 5,
      q_mucosa_ulcer_duration: 0,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P20',
    name: '口腔癌高危病例',
    profile: { ageGroup: '62岁', gender: '男', desc: '62岁男性，抽烟喝酒30余年。右舌边缘有个溃疡超过一个月不愈合，边缘摸起来硬邦邦的，那块舌头的感觉也变麻木了。最近两个月体重掉了5公斤。' },
    target: 'oral_cancer',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 1,
      q_mucosa_ulcer_pattern: 5,
      q_mucosa_ulcer_duration: 1,
      q_mucosa_cancer_redflags: [0, 1, 2, 3],
      q_universal_age: 3,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P21',
    name: '口腔白斑病例',
    profile: { ageGroup: '55岁', gender: '男', desc: '55岁男性，抽烟30年每天一包，左颊黏膜发现一块擦不掉的白色斑块，表面摸着有些粗糙，没有疼痛感，但张嘴大了感觉紧绷。' },
    target: 'leukoplakia',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 0,
      q_mucosa_white_risk: 0,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P22',
    name: '口腔黏膜下纤维化(OSF)病例',
    profile: { ageGroup: '38岁', gender: '男', desc: '38岁男性，嚼槟榔15年，口腔黏膜逐渐变白变硬，嘴巴越来越张不开了，现在连一根手指都塞不进去。说话和吃东西都困难。' },
    target: 'osf',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 0,
      q_mucosa_white_risk: 1,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 2,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P23',
    name: '口腔扁平苔藓病例',
    profile: { ageGroup: '46岁', gender: '女', desc: '46岁女性，两颊内侧出现白色网状条纹很长时间了，偶尔会糜烂疼痛，反反复复。有轻度焦虑史。' },
    target: 'lichen_planus',
    category: 'mucosa',
    urgency: 'yellow',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 0,
      q_mucosa_white_risk: 2,
      q_universal_age: 2,
      q_universal_gender: 0,
      q_universal_medical: 2,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P24',
    name: '口腔念珠菌病病例',
    profile: { ageGroup: '72岁', gender: '男', desc: '72岁男性，有糖尿病史，戴满口假牙多年。嘴里出现一层白色奶酪样的膜，能擦掉，擦掉后黏膜红红的。口干得厉害。' },
    target: 'candidiasis',
    category: 'mucosa',
    urgency: 'yellow',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 0,
      q_universal_age: 3,
      q_universal_gender: 1,
      q_universal_medical: 0,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P25',
    name: '疱疹性口炎病例',
    profile: { ageGroup: '6岁', gender: '女', desc: '6岁女童，发烧两天后嘴里出现成簇的小水疱，破了以后连成一片糜烂，唇部和上颚明显。流口水、不肯吃东西喝水。' },
    target: 'herpes_stomatitis',
    category: 'mucosa',
    urgency: 'yellow',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 1,
      q_mucosa_ulcer_pattern: 5,
      q_mucosa_ulcer_duration: 3,
      q_universal_age: 0,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P26',
    name: '天疱疮病例',
    profile: { ageGroup: '52岁', gender: '女', desc: '52岁女性，口腔大面积糜烂三个月了，吃饭咽水都疼，身上也出现松弛的大水疱，用手指推一下疱就扩大（尼氏征阳性）。' },
    target: 'pemphigus',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 1,
      q_mucosa_ulcer_pattern: 5,
      q_mucosa_ulcer_duration: 2,
      q_universal_age: 2,
      q_universal_gender: 0,
      q_universal_medical: 2,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  // ==================== 颌面关节 (JOINT) - 6例 ====================

  {
    id: 'P27',
    name: 'TMD典型病例',
    profile: { ageGroup: '28岁', gender: '女', desc: '28岁女性，张嘴闭嘴时右侧耳前关节处有明显的\"咔咔\"弹响声，咀嚼硬东西时酸胀不适，但没有早上的酸胀感。' },
    target: 'tmd',
    category: 'joint',
    urgency: 'green',
    answers: {
      q_entry: 4,
      q_jaw_recent_extraction: 1,
      q_jaw_bisphosphonate: 1,
      q_jaw_pain_or_noise: 0,
      q_jaw_morning_stiff: 1,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 2,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P28',
    name: '夜磨牙病例',
    profile: { ageGroup: '35岁', gender: '男', desc: '35岁男性，每天早上醒来腮帮子酸痛，妻子说他晚上磨牙声很大。牙齿咬合面磨损明显，对冷热也开始敏感了。' },
    target: 'bruxism',
    category: 'joint',
    urgency: 'yellow',
    answers: {
      q_entry: 4,
      q_jaw_recent_extraction: 1,
      q_jaw_bisphosphonate: 1,
      q_jaw_pain_or_noise: 0,
      q_jaw_morning_stiff: 0,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 2,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P29',
    name: '三叉神经痛病例',
    profile: { ageGroup: '65岁', gender: '女', desc: '65岁女性，右侧脸颊反复出现闪电式/刀割样的剧烈疼痛，每次持续几十秒，洗脸、刷牙甚至吹到风都能触发。在口腔科查了几次也没发现牙齿有什么问题。' },
    target: 'trigeminal_neuralgia',
    category: 'joint',
    urgency: 'yellow',
    answers: {
      q_entry: 0,
      q_pain_spontaneous: 1,
      q_pain_cold_hot_diff: 0,
      q_pain_trigger_main: 2,
      q_pain_lightning_duration: 0,
      q_pain_xray_finding: 1,
      q_universal_age: 3,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P30',
    name: '牙齿外伤病例',
    profile: { ageGroup: '15岁', gender: '男', desc: '15岁男生，打篮球时不慎摔倒，门牙整颗从牙槽窝完全掉出来了。牙槽窝还在流血，人很慌张。' },
    target: 'trauma',
    category: 'joint',
    urgency: 'red',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 0,
      q_hard_defect_type: 3,
      q_hard_trauma_type: 0,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P31',
    name: '涎石症病例',
    profile: { ageGroup: '48岁', gender: '男', desc: '48岁男性，每次吃饭的时候右边下巴下面就肿起来一个大包，疼，吃完饭后过一两个小时就自己消退下去了。反复发作了几个月。' },
    target: 'sialolithiasis',
    category: 'joint',
    urgency: 'yellow',
    answers: {
      q_entry: 4,
      q_jaw_recent_extraction: 1,
      q_jaw_bisphosphonate: 1,
      q_jaw_pain_or_noise: 1,
      q_jaw_swelling_meal: 0,
      q_universal_age: 2,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P32',
    name: '腮腺炎病例',
    profile: { ageGroup: '12岁', gender: '男', desc: '12岁男生，右侧耳垂下方肿起来了，按压很疼，同时发烧到38.5°C，全身没力气不想吃东西。班里最近也有几个同学腮帮子肿起来。' },
    target: 'parotitis',
    category: 'joint',
    urgency: 'yellow',
    answers: {
      q_entry: 4,
      q_jaw_recent_extraction: 1,
      q_jaw_bisphosphonate: 1,
      q_jaw_pain_or_noise: 1,
      q_jaw_swelling_meal: 1,
      q_universal_age: 0,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 1,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  // ==================== 其他/系统 (OTHER) - 8例 ====================

  {
    id: 'P33',
    name: '非口源性口臭病例',
    profile: { ageGroup: '35岁', gender: '男', desc: '35岁男性，口腔卫生习惯良好（早晚刷牙、用牙线、定期洗牙），但口臭问题一直很严重，同事经常侧过脸说话。偶尔反酸、胃胀。' },
    target: 'halitosis',
    category: 'other',
    urgency: 'green',
    answers: {
      q_entry: 5,
      q_systemic_dry_or_burn: 2,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P34',
    name: '口干症（干燥综合征疑似）',
    profile: { ageGroup: '55岁', gender: '女', desc: '55岁女性，长期口干舌燥，喝很多水还是干，说话久了嗓子变哑，眼睛也特别干涩。同时有类风湿关节炎病史。' },
    target: 'xerostomia',
    category: 'other',
    urgency: 'yellow',
    answers: {
      q_entry: 5,
      q_systemic_dry_or_burn: 0,
      q_systemic_dry_cause: 1,
      q_universal_age: 2,
      q_universal_gender: 0,
      q_universal_medical: 2,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P35',
    name: '灼口综合征病例',
    profile: { ageGroup: '58岁', gender: '女', desc: '58岁女性，绝经后出现持续的口腔烧灼感，从早晨起来就开始，舌头尤其明显。但口腔科检查黏膜完全正常。睡眠也不太好。' },
    target: 'burning_mouth',
    category: 'other',
    urgency: 'green',
    answers: {
      q_entry: 5,
      q_systemic_dry_or_burn: 1,
      q_universal_age: 2,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P36',
    name: '放射性口炎病例',
    profile: { ageGroup: '62岁', gender: '男', desc: '62岁男性，鼻咽癌放疗三个月后，整个口腔黏膜发红糜烂，疼得吃不了东西，口干如沙漠，牙齿也开始快速蛀坏了。' },
    target: 'radiation_stomatitis',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 1,
      q_perio_necrosis_smell: 1,
      q_perio_bleeding_type: 1,
      q_perio_mobility: 0,
      q_perio_age_rapid: 1,
      q_universal_age: 3,
      q_universal_gender: 1,
      q_universal_medical: 4,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 0,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P37',
    name: '氟斑牙病例',
    profile: { ageGroup: '28岁', gender: '女', desc: '28岁女性，牙齿从小就有白垩色和黄褐色斑块，影响美观，害怕大笑露齿。小时候一直在高氟地区（河北某地）长大。' },
    target: 'fluorosis',
    category: 'other',
    urgency: 'green',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 1,
      q_hard_dev_color_or_shape: 0,
      q_hard_dev_color_detail: 0,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P38',
    name: '四环素牙病例',
    profile: { ageGroup: '45岁', gender: '男', desc: '45岁男性，牙齿从换牙之后就是灰黄褐色，小时候每次感冒发烧家里就给他吃四环素（上世纪80年代常用）。影响美观。' },
    target: 'tetracycline_teeth',
    category: 'other',
    urgency: 'green',
    answers: {
      q_entry: 3,
      q_hard_acquired_or_dev: 1,
      q_hard_dev_color_or_shape: 0,
      q_hard_dev_color_detail: 1,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 0,
    }
  },

  {
    id: 'P39',
    name: '综合高风险病例',
    profile: { ageGroup: '42岁', gender: '男', desc: '42岁男性，抽烟20年每天一包，喝酒一周5次，还嚼槟榔10年。口腔多处白斑、张口困难、牙齿松动、牙龈出血、口臭严重。全方位高风险。' },
    target: 'multiple',
    category: 'mucosa',
    urgency: 'red',
    answers: {
      q_entry: 2,
      q_mucosa_can_scrape: 1,
      q_mucosa_white_or_ulcer: 0,
      q_mucosa_white_risk: 1,
      q_universal_age: 1,
      q_universal_gender: 1,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 0,
      q_universal_brush: 1,
      q_universal_stress: 0,
      q_universal_diet: 2,
      q_universal_dental_visit: 1,
      q_universal_fluoride: 1,
    }
  },

  {
    id: 'P40',
    name: '健康口腔病例（对照）',
    profile: { ageGroup: '30岁', gender: '女', desc: '30岁女性，无症状常规检查，口腔卫生良好，规律刷牙、用牙线、定期洗牙，不抽烟不喝酒，饮食均衡，作息规律。这个病例用于测试系统对健康用户的判定。' },
    target: null,
    category: 'none',
    urgency: 'green',
    answers: {
      q_entry: 4,
      q_jaw_recent_extraction: 1,
      q_jaw_bisphosphonate: 1,
      q_jaw_pain_or_noise: 0,
      q_jaw_morning_stiff: 1,
      q_universal_age: 1,
      q_universal_gender: 0,
      q_universal_medical: 6,
      q_universal_family: 3,
      q_universal_smoking: 3,
      q_universal_brush: 2,
      q_universal_stress: 2,
      q_universal_diet: 3,
      q_universal_dental_visit: 0,
      q_universal_fluoride: 0,
    }
  },
];

// 疾病类别映射（用于统计）
const CATEGORY_LABELS = {
  tooth: '牙体牙髓',
  perio: '牙周',
  mucosa: '黏膜',
  joint: '颌面/关节/神经',
  other: '其他/系统'
};

const URGENCY_LABELS = {
  green: '绿色（常规）',
  yellow: '黄色（需关注）',
  red: '红色（紧急）'
};

// 导出
if (typeof module !== 'undefined' && module.exports) {
  module.exports = { PATIENT_CASES, CATEGORY_LABELS, URGENCY_LABELS };
}
